image: louisbb/docker-compose-ssh:latest

stages:
  - build
  - test
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: docker.xiaosolar.com/backend/crm-api/develop:latest
  CONTAINER_PROD_IMAGE: docker.xiaosolar.com/backend/crm-api/production:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.xiaosolar.com

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - shared-runner-tag

test:
  stage: test
  script:
    - docker ps
  tags:
    - shared-runner-tag

release_prod_image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_PROD_IMAGE
    - docker push $CONTAINER_PROD_IMAGE
  tags:
    - shared-runner-tag
  only:
    - master

deploy_develop:
  stage: deploy
  script: 
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -p22 henry@106.14.210.95 "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.xiaosolar.com"
    - ssh -p22 henry@106.14.210.95 "[ -f ~/crm-api/docker-compose.test.yml ] && docker-compose -f ~/crm-api/docker-compose.test.yml down || mkdir ~/crm-api"
    - scp -P22 docker-compose.test.yml henry@106.14.210.95:crm-api
    - ssh -p22 henry@106.14.210.95 "docker pull $CONTAINER_TEST_IMAGE"
    - ssh -p22 henry@106.14.210.95 "docker-compose -f ~/crm-api/docker-compose.test.yml up -d"
  tags:
    - shared-runner-tag
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -p22 henry@47.100.206.81 "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.xiaosolar.com"
    - ssh -p22 henry@47.100.206.81 "[ -f ~/crm-api/docker-compose.production.yml ] && docker-compose -f ~/crm-api/docker-compose.production.yml down || mkdir ~/crm-api"
    - scp -P22 docker-compose.production.yml henry@47.100.206.81:crm-api
    - ssh -p22 henry@47.100.206.81 "docker pull $CONTAINER_PROD_IMAGE"
    - ssh -p22 henry@47.100.206.81 "docker-compose -f ~/crm-api/docker-compose.production.yml up -d"
  tags:
    - shared-runner-tag
  only:
    - master
