image: louisbb/docker-compose-ssh:latest

stages:
  - build
  - test
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: docker.xiaosolar.com/xq/front-api/develop:latest
  CONTAINER_PROD_IMAGE: docker.xiaosolar.com/xq/front-api/production:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.xiaosolar.com

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - front-api

test:
  stage: test
  script:
    - docker ps
  tags:
    - front-api

release_prod_image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_PROD_IMAGE
    - docker push $CONTAINER_PROD_IMAGE
  tags:
    - front-api
  only:
    - master

deploy_develop:
  stage: deploy
  script: 
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -p22 henry@106.14.210.95 "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.niuchuangwin.com"
    - ssh -p22 henry@106.14.210.95 "[ -f ~/front-api/docker-compose.testing.yml ] && docker-compose -f ~/front-api/docker-compose.testing.yml down || mkdir ~/front-api"
    - scp -P22 docker-compose.testing.yml henry@106.14.210.95:front-api
    - ssh -p22 henry@106.14.210.95 "docker pull $CONTAINER_TEST_IMAGE"
    - ssh -p22 henry@106.14.210.95 "docker-compose -f ~/front-api/docker-compose.testing.yml up -d"
  tags:
    - front-api
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -p22 henry@52.80.89.188 "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.niuchuangwin.com"
    - ssh -p22 henry@52.80.89.188 "[ -f ~/front-api/docker-compose.production.yml ] && docker-compose -f ~/front-api/docker-compose.production.yml down || mkdir ~/front-api"
    - scp -P22 docker-compose.production.yml henry@52.80.89.188:front-api
    - ssh -p22 henry@52.80.89.188 "docker pull $CONTAINER_PROD_IMAGE"
    - ssh -p22 henry@52.80.89.188 "docker-compose -f ~/front-api/docker-compose.production.yml up -d"
  tags:
    - front-api
  only:
    - master
