version: "3"

networks:
  lb_traefiknet:
    external: true

services:
  front-api:
    image: docker.xiaosolar.com/xq/front-api/develop:latest
    restart: always
    ports:
      - "7001:7001"
    networks:
      - lb_traefiknet
    volumes:
      - /srv/docker/front-api/logs:/home/node/logs
    environment:
      - NODE_ENV=development
      - EGG_SERVER_ENV=test
    command: "npm run non-daemon-start"
    labels:
      - "traefik.port=7001"
      - "traefik.network=traefiknet"
      - "traefik.frontend.rule=Host:mpa.xiaosolar.com;PathPrefixStrip:/front-api"
      - "traefik.backend=front-api"
