version: "3"

networks:
  lb_traefiknet:
    external: true
  redis_redisnet:
    external: true

services:
  crm-api:
    image: docker.xiaosolar.com/backend/crm-api/production:latest
    restart: always
    external_links:
      - redis_redis_1:redis
    networks:
      - lb_traefiknet
      - redis_redisnet
    volumes:
      - /srv/docker/crm-api/logs:/home/node/logs
    environment:
      - NODE_ENV=production
      - EGG_SERVER_ENV=prod
    command: "npm run non-daemon-start"
    labels:
      - "traefik.port=7001"
      - "traefik.network=traefiknet"
      - "traefik.frontend.rule=Host:mp.xiaosolar.com;PathPrefixStrip:/crm-api"
      - "traefik.backend=crm-api"
